name: Docker Build & Artifactory Push

on:
  workflow_call:
    inputs:
      artifact_registry:
        required: true
        type: string
        default: europe-west1-docker.pkg.dev
      project_id:
        required: true
        type: string
        default: meisterlabs-prod
      repository:
        required: true
        type: string
        default: custom-images
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
        default: latest

jobs:        
  build:
    runs-on: [self-hosted, keda, default]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Auth to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Artifact Registry
      run: gcloud auth configure-docker ${{ inputs.artifact_registry }}

    - name: Get tag
      id: get-tag
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: TARGET_PRODUCT_FILE=${{ inputs.product }}-packages.sh
        tags: |
           ${{ inputs.artifact_registry }}/${{ inputs.project_id }}/${{ inputs.repository }}/${{ inputs.image }}:${{ steps.get-tag.outputs.short_ref }}
           ${{ inputs.artifact_registry }}/${{ inputs.project_id }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
