name: Docker Build and GCAR Push

on:
  workflow_dispatch:
    inputs:
      product:
        type: choice
        options:
          - ode
          - accounts
          - meisternote
          - meistertask
          - mindmeister
          - none
      tag:
        type: string
        required: true

jobs:
  build_and_push:
    uses: ./.github/workflows/ci-build-push.yaml
    secrets: inherit
    with:
      image: ${{ inputs.product }}
      tag: ${{ inputs.tag }}
