---
    name: Renovate
    
    on:
      schedule:
        - cron: '0 0 * * *'  # Run daily (adjust the schedule as needed)
    
    jobs:
      renovate:
        runs-on: [self-hosted, keda, default]
    
        steps:
          - name: Use Custom Renovate Action
            uses: ./.github/actions/renovate@main
            with:
              RENOVATE_GH_APP_ID: ${{ secrets.RENOVATE_GH_APP_ID }}
              RENOVATE_GH_APP_PRIVATE_KEY: ${{ secrets.RENOVATE_GH_APP_PRIVATE_KEY }}
